# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

TARGET = list_sq
# Points to the root of Google Test, relative to where this file is.
# Remember to tweak this if you move this file.
GTEST_DIR = ./gtest

# Where to find user code.
SRC_DIR = ./src
TEST_DIR = ./test

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CXX = g++-8
CPPFLAGS += -isystem $(GTEST_DIR)/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -pthread -gdwarf-3

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = $(TARGET)_test

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS)

clean :
	rm -f $(TESTS) gtest.a gtest_main.a *.o

# Builds gtest.a and gtest_main.a.

# Usually you shouldn't tweak such internal variables, indicated by a
# trailing _.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

# For simplicity and to avoid depending on Google Test's
# implementation details, the dependencies specified below are
# conservative and not optimized.  This is fine as Google Test
# compiles fast and for ordinary users its source rarely changes.
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc -o $(addprefix build/,$@)

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc -o $(addprefix build/,$@)


gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $(addprefix build/,$@) $(addprefix build/,$^)

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $(addprefix build/,$@) $(addprefix build/,$^)

# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

$(TARGET).o : $(SRC_DIR)/$(TARGET).cpp $(SRC_DIR)/$(TARGET).hpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(SRC_DIR)/$(TARGET).cpp -o $(addprefix build/,$@)

$(TARGET)_test.o : $(TEST_DIR)/$(TARGET)_test.cpp \
                     $(SRC_DIR)/$(TARGET).hpp $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(TEST_DIR)/$(TARGET)_test.cpp -o $(addprefix build/,$@)

$(TARGET)_test : $(TARGET).o $(TARGET)_test.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS)  $(addprefix build/,$^) -lpthread -o $(addprefix bin/,test)
